---

auth_url: ((auth_url))
project_domain_name: ((openstack_domain))
project_name: ((openstack_project))
user_domain_name: ((openstack_domain))
username: ((openstack_username))
password: ((openstack_password))
vm_name: ((opsman_instance_name))
flavor:
availability_zone:
key_pair_name:
security_group_name:
net_id:
public_ip:
private_ip:
