# az-configuration:
# - name: AZ0
network-assignment:
  network:
    name: pcf-management
  other_availability_zones: []
  singleton_availability_zone:
    name: ((singleton_availability_zone))
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: pcf-management
    subnets:
    - iaas_identifier: ((management_network_iaas_identifier))
      cidr: ((management_network_cidr))
      dns: ((management_network_dns))
      gateway: ((management_network_gateway))
      reserved_ip_ranges: ((management_network_reserved_ip_ranges))
      availability_zone_names: ((management_network_availability_zone_names))
properties-configuration:
  director_configuration:
    blobstore_type: local
    bosh_recreate_on_next_deploy: false
    bosh_recreate_persistent_disks_on_next_deploy: false
    database_type: internal
    director_worker_count: 5
    encryption:
      keys: []
      providers: []
    hm_emailer_options:
      enabled: false
    hm_pager_duty_options:
      enabled: false
    identification_tags: {}
    job_configuration_on_tmpfs: false
    keep_unreachable_vms: false
    local_blobstore_options:
      tls_enabled: true
    ntp_servers_string: ((ntp_servers))
    post_deploy_enabled: true
    resurrector_enabled: true
    retry_bosh_deploys: false
    skip_director_drain: false
  dns_configuration:
    excluded_recursors: []
    handlers: []
  advanced_infrastructure_config:
    connection_options: ((connection_options))
  iaas_configuration:
    name: ((name))
    keystone_version: ((keystone_version))
    identity_endpoint: ((identity_endpoint))
    domain: ((domain))
    tenant: ((tenant))
    username: ((username))
    password: ((password))
    region: ((region))
    networking_model: ((networking_model))
    security_group: ((security_group))
    key_pair_name: ((key_pair_name))
    boot_from_volume: ((boot_from_volume))
    additional_cloud_properties: ((additional_cloud_properties))
    ignore_server_availability_zone: ((ignore_server_availability_zone))
    disable_dhcp: ((disable_dhcp))
    ssh_private_key: ((ssh_private_key))
  security_configuration:
    generate_vm_passwords: true
    opsmanager_root_ca_trusted_certs: true
  syslog_configuration:
    enabled: false
resource-configuration:
  compilation:
    instances: automatic
    instance_type:
      id: automatic
  director:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
vmextensions-configuration: []

