product-name: pas-windows
product-properties:
  .properties.bosh_ssh_enabled:
    value: true
  .properties.kms:
    selected_option: disable
    value: disable
  .properties.rdp_enabled:
    value: true
  .properties.smoke_tests_windows:
    selected_option: on_demand
    value: on_demand
  .properties.system_logging:
    selected_option: disable
    value: disable
  .properties.windows_admin_password:
    selected_option: set_password
    value: set_password
  .properties.windows_admin_password.set_password.password:
    value:
      secret: ((windows_admin_password))
network-properties:
  network:
    name: ((network_name))
  other_availability_zones: ((availability_zones))
  singleton_availability_zone:
    name: ((singleton_availability_zone))
resource-config:
  windows_diego_cell:
    instances: ((num_compute_instances))
    instance_type:
      id: automatic
errand-config:
  install-hwc-buildpack:
    post-deploy-state: true
  smoke_tests_windows:
    post-deploy-state: false
