---

vcenter_ip: ((vcenter_ip))
vcenter_user: ((vcenter_user))
vcenter_password: ((vcenter_password))
vcenter_datacenter:
vcenter_datastore:
vcenter_resource_pool:
vcenter_vm_folder: ((vcenter_vm_folder))

opsman_vm_name:
opsman_disk_type:
opsman_vm_memory:
opsman_vm_cpu:
opsman_private_ip:
opsman_dns:
opsman_ntp:
opsman_network:
opsman_netmask:
opsman_gateway:
opsman_host: ((opsman_host))
opsman_ssh_password: ((opsman_ssh_password))
opsman_ssh_public_key:
