---
network_name:
availability_zones:
- name:
singleton_availability_zone:

apps_domain:
system_domain:

ha_proxy_static_ips:
router_static_ips:
tcp_router_static_ips:
diego_brain_static_ips:

mysql_monitor_recipient_email:

num_mysql_monitor_instances:
num_control_instances:
num_compute_instances:
num_router_instances:
num_ha_proxy_instances:

branding_company_name:
branding_product_logo:
branding_square_logo:
branding_footer_legal_text:

# Openstack only
ha_proxy_floating_ip:
router_floating_ip:

#
# Certificates and passwords from credhub
#

haproxy_forward_tls_backend_ca: |
  ((default_ca.ca))

routing_custom_ca_certificates: |
  ((default_ca.ca))

default_networking_poe_tls_cert: ((pas_default_networking_poe_tls.certificate))
default_networking_poe_tls_key: ((pas_default_networking_poe_tls.private_key))

uaa_service_provider_cert: ((pas_uaa_service_provider.certificate))
uaa_service_provider_key: ((pas_uaa_service_provider.private_key))

default_credhub_encryption_key: ((pas_default_credhub_encryption_key))
