# bosh -n -d pdf-generator-service deploy manifest.yml \
#   --var=deployment_name=pdf-generator-service \
#   --var=stemcell_os_name=windows2012R2 \
#   --var=admin_password=D3DPaSW@2020 \
#   --var=vm_size=medium \
#   --var=network=pcf-releng \
#   --var=public_ip=172.28.112.17

name: ((deployment_name))

releases:
- name: windows-vm
  version: latest
- name: windows-utilities
  version: latest

stemcells:
- alias: windows
  os: ((stemcell_os_name))
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-300000
  update_watch_time: 30000-300000

instance_groups:
- name: ((stemcell_os_name))
  azs: [AZ0]
  instances: 1
  jobs:
  - name: run
    release: windows-vm
  - name: enable_rdp
    release: windows-utilities
    properties:
      enable_rdp:
        enabled: true
  - name: set_password
    release: windows-utilities
    properties:
      set_password:
        password: ((admin_password))
  vm_type: ((vm_size))
  stemcell: windows
  networks:
  - name: ((network))
    default:
    - dns
    - gateway
  - name: public
    static_ips:
    - ((public_ip))
