---
opsman-configuration:
  openstack:
    insecure: true
    identity_api_version: 3
    auth_url: ((auth_url))
    project_domain_name: ((project_domain_name))
    project_name: ((project_name))
    user_domain_name: ((user_domain_name))
    username: ((username))
    password: ((password))
    vm_name: ((vm_name))
    flavor: ((flavor))
    availability_zone: ((availability_zone))
    key_pair_name: ((key_pair_name))
    security_group_name: ((security_group_name))
    net_id: ((net_id))
    public_ip: ((public_ip))
    private_ip: ((private_ip))
