network-assignment:
  network:
    name: infrastructure
  other_availability_zones:
  - name: "null"
  singleton_availability_zone:
    name: "null"
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: infrastructure
    subnets:
    - iaas_identifier: pcfazure-virtual-network/pcfazure-infrastructure-subnet
      cidr: 10.0.8.0/26
      dns: 168.63.129.16
      gateway: 10.0.8.1
      reserved_ip_ranges: 10.0.8.1-10.0.8.9
      availability_zone_names:
      - "null"
  - name: pas
    subnets:
    - iaas_identifier: pcfazure-virtual-network/pcfazure-pas-subnet
      cidr: 10.0.0.0/22
      dns: 168.63.129.16
      gateway: 10.0.0.1
      reserved_ip_ranges: 10.0.0.1-10.0.0.9
      availability_zone_names:
      - "null"
  - name: services
    subnets:
    - iaas_identifier: pcfazure-virtual-network/pcfazure-services-subnet
      cidr: 10.0.4.0/22
      dns: 168.63.129.16
      gateway: 10.0.4.1
      reserved_ip_ranges: 10.0.4.1-10.0.4.9
      availability_zone_names:
      - "null"
properties-configuration:
  director_configuration:
    allow_legacy_agents: true
    blobstore_type: local
    bosh_recreate_on_next_deploy: true
    bosh_recreate_persistent_disks_on_next_deploy: true
    database_type: internal
    director_worker_count: 5
    encryption:
      keys: []
      providers: []
    hm_emailer_options:
      enabled: false
    hm_pager_duty_options:
      enabled: false
    identification_tags: {}
    keep_unreachable_vms: true
    local_blobstore_options:
      tls_enabled: true
    ntp_servers_string: time.windows.com
    post_deploy_enabled: true
    resurrector_enabled: true
    retry_bosh_deploys: true
  dns_configuration:
    excluded_recursors: []
    handlers: []
  iaas_configuration:
    additional_cloud_properties: {}
    bosh_storage_account_name: py8qk63z3ototrb7adze
    client_id: ((client_id))
    client_secret: ((client_secret))
    cloud_storage_type: managed_disks
    default_security_group: pcfazure-bosh-deployed-vms-security-group
    environment: AzureCloud
    name: default
    resource_group_name: pcfazure
    ssh_private_key: ((ssh_private_key))
    ssh_public_key: ((ssh_public_key))
    storage_account_type: Premium_LRS
    subscription_id: ((subscription_id))
    tenant_id: ((tenant_id))
  security_configuration:
    generate_vm_passwords: true
    opsmanager_root_ca_trusted_certs: true
  syslog_configuration:
    enabled: false
resource-configuration:
  compilation:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: false
  director:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: false
vmextensions-configuration: []